/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by vite-plugin-uni-pages

type _LocationUrl =
  "/pages/home/index" |
  "/pages/mine/index" |
  "/pages/recommend/index" |
  "/pages/test/index" |
  "/pages/testMine/index" |
  "/pages-sub/homedoctor/detail/index" |
  "/pages-sub/signup/form/index" |
  "/pages-sub/signup/result/index" |
  "/pages-sub/signuprights/index" |
  "/pages-sub/submine/detalSign/index" |
  "/pages-sub/submine/doctorrecommendation/index" |
  "/pages-sub/submine/healthrecord/index" |
  "/pages-sub/submine/homedoctor/addCertification" |
  "/pages-sub/submine/homedoctor/addFimalyPerson" |
  "/pages-sub/submine/homedoctor/index" |
  "/pages-sub/submine/homedoctor/rulesNotice" |
  "/pages-sub/submine/signinformation/index" |
  "/pages-sub/submine/signinterests/index" |
  "/pages-sub/submine/userInfoEdit/index";

interface NavigateToOptions {
  url: _LocationUrl;
}
interface RedirectToOptions extends NavigateToOptions {}

interface SwitchTabOptions {
  url: "/pages/home/index" | "/pages/recommend/index" | "/pages/mine/index"
}

type ReLaunchOptions = NavigateToOptions | SwitchTabOptions;

declare interface Uni {
  navigateTo(options: UniNamespace.NavigateToOptions & NavigateToOptions): void;
  redirectTo(options: UniNamespace.RedirectToOptions & RedirectToOptions): void;
  switchTab(options: UniNamespace.SwitchTabOptions & SwitchTabOptions): void;
  reLaunch(options: UniNamespace.ReLaunchOptions & ReLaunchOptions): void;
}

declare module "virtual:uni-pages" {
  export type LocationUrl = _LocationUrl;
}
