/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by vite-plugin-uni-pages

type _LocationUrl =
  "/pages/home/index" |
  "/pages/cart/index" |
  "/pages/category/index" |
  "/pages/mine/index" |
  "/pages-sub/mine/address/edit" |
  "/pages-sub/home-category/list/index" |
  "/pages-sub/home-seasonal/list/index" |
  "/pages-sub/mine/address/index" |
  "/pages-sub/mine/member/index" |
  "/pages-sub/mine/orders/index" |
  "/pages-sub/mine/recharge/index" |
  "/pages-sub/mine/reviews/index" |
  "/pages-sub/mine/security/index" |
  "/pages-sub/mine/service/index" |
  "/pages-sub/product/detail/index";

interface NavigateToOptions {
  url: _LocationUrl;
}
interface RedirectToOptions extends NavigateToOptions {}

interface SwitchTabOptions {
  url: "/pages/home/index" | "/pages/category/index" | "/pages/cart/index" | "/pages/mine/index"
}

type ReLaunchOptions = NavigateToOptions | SwitchTabOptions;

declare interface Uni {
  navigateTo(options: UniNamespace.NavigateToOptions & NavigateToOptions): void;
  redirectTo(options: UniNamespace.RedirectToOptions & RedirectToOptions): void;
  switchTab(options: UniNamespace.SwitchTabOptions & SwitchTabOptions): void;
  reLaunch(options: UniNamespace.ReLaunchOptions & ReLaunchOptions): void;
}

declare module "virtual:uni-pages" {
  export type LocationUrl = _LocationUrl;
}
